/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BrowserAutomationGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Model");
		private final Assignment cTisiAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTisiTestParserRuleCall_0 = (RuleCall)cTisiAssignment.eContents().get(0);
		
		//Model:
		//	tisi+=Test*;
		@Override public ParserRule getRule() { return rule; }
		
		//tisi+=Test*
		public Assignment getTisiAssignment() { return cTisiAssignment; }
		
		//Test
		public RuleCall getTisiTestParserRuleCall_0() { return cTisiTestParserRuleCall_0; }
	}
	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cONKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cBAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBBrowserParserRuleCall_1_0 = (RuleCall)cBAssignment_1.eContents().get(0);
		private final Keyword cGOTOKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUUrlParserRuleCall_3_0 = (RuleCall)cUAssignment_3.eContents().get(0);
		private final Keyword cISKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cATTRIBUTKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cA1Assignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cA1AttributParserRuleCall_6_0 = (RuleCall)cA1Assignment_6.eContents().get(0);
		private final Keyword cWHEREKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cATTRIBUTKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cA2Assignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cA2AttributParserRuleCall_9_0 = (RuleCall)cA2Assignment_9.eContents().get(0);
		private final Keyword cCONTAINSKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cQuotationMarkKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final RuleCall cSTRINGTerminalRuleCall_12 = (RuleCall)cGroup.eContents().get(12);
		private final Keyword cQuotationMarkKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Test:
		//	'ON' b=Browser 'GOTO' u=Url 'IS' 'ATTRIBUT' a1=Attribut 'WHERE' 'ATTRIBUT' a2=Attribut 'CONTAINS' '"' STRING '"';
		@Override public ParserRule getRule() { return rule; }
		
		//'ON' b=Browser 'GOTO' u=Url 'IS' 'ATTRIBUT' a1=Attribut 'WHERE' 'ATTRIBUT' a2=Attribut 'CONTAINS' '"' STRING '"'
		public Group getGroup() { return cGroup; }
		
		//'ON'
		public Keyword getONKeyword_0() { return cONKeyword_0; }
		
		//b=Browser
		public Assignment getBAssignment_1() { return cBAssignment_1; }
		
		//Browser
		public RuleCall getBBrowserParserRuleCall_1_0() { return cBBrowserParserRuleCall_1_0; }
		
		//'GOTO'
		public Keyword getGOTOKeyword_2() { return cGOTOKeyword_2; }
		
		//u=Url
		public Assignment getUAssignment_3() { return cUAssignment_3; }
		
		//Url
		public RuleCall getUUrlParserRuleCall_3_0() { return cUUrlParserRuleCall_3_0; }
		
		//'IS'
		public Keyword getISKeyword_4() { return cISKeyword_4; }
		
		//'ATTRIBUT'
		public Keyword getATTRIBUTKeyword_5() { return cATTRIBUTKeyword_5; }
		
		//a1=Attribut
		public Assignment getA1Assignment_6() { return cA1Assignment_6; }
		
		//Attribut
		public RuleCall getA1AttributParserRuleCall_6_0() { return cA1AttributParserRuleCall_6_0; }
		
		//'WHERE'
		public Keyword getWHEREKeyword_7() { return cWHEREKeyword_7; }
		
		//'ATTRIBUT'
		public Keyword getATTRIBUTKeyword_8() { return cATTRIBUTKeyword_8; }
		
		//a2=Attribut
		public Assignment getA2Assignment_9() { return cA2Assignment_9; }
		
		//Attribut
		public RuleCall getA2AttributParserRuleCall_9_0() { return cA2AttributParserRuleCall_9_0; }
		
		//'CONTAINS'
		public Keyword getCONTAINSKeyword_10() { return cCONTAINSKeyword_10; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_11() { return cQuotationMarkKeyword_11; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_12() { return cSTRINGTerminalRuleCall_12; }
		
		//'"'
		public Keyword getQuotationMarkKeyword_13() { return cQuotationMarkKeyword_13; }
	}
	public class BrowserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Browser");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Browser:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class UrlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Url");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Url:
		//	name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=STRING
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0() { return cNameSTRINGTerminalRuleCall_0; }
	}
	public class AttributElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Attribut");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Attribut:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class GreetingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Greeting");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHelloKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Greeting:
		//	'Hello' name=ID '!';
		@Override public ParserRule getRule() { return rule; }
		
		//'Hello' name=ID '!'
		public Group getGroup() { return cGroup; }
		
		//'Hello'
		public Keyword getHelloKeyword_0() { return cHelloKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'!'
		public Keyword getExclamationMarkKeyword_2() { return cExclamationMarkKeyword_2; }
	}
	
	
	private final ModelElements pModel;
	private final TestElements pTest;
	private final BrowserElements pBrowser;
	private final UrlElements pUrl;
	private final AttributElements pAttribut;
	private final GreetingElements pGreeting;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BrowserAutomationGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pTest = new TestElements();
		this.pBrowser = new BrowserElements();
		this.pUrl = new UrlElements();
		this.pAttribut = new AttributElements();
		this.pGreeting = new GreetingElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.BrowserAutomation".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	tisi+=Test*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Test:
	//	'ON' b=Browser 'GOTO' u=Url 'IS' 'ATTRIBUT' a1=Attribut 'WHERE' 'ATTRIBUT' a2=Attribut 'CONTAINS' '"' STRING '"';
	public TestElements getTestAccess() {
		return pTest;
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}
	
	//Browser:
	//	name=ID;
	public BrowserElements getBrowserAccess() {
		return pBrowser;
	}
	
	public ParserRule getBrowserRule() {
		return getBrowserAccess().getRule();
	}
	
	//Url:
	//	name=STRING;
	public UrlElements getUrlAccess() {
		return pUrl;
	}
	
	public ParserRule getUrlRule() {
		return getUrlAccess().getRule();
	}
	
	//Attribut:
	//	name=ID;
	public AttributElements getAttributAccess() {
		return pAttribut;
	}
	
	public ParserRule getAttributRule() {
		return getAttributAccess().getRule();
	}
	
	//Greeting:
	//	'Hello' name=ID '!';
	public GreetingElements getGreetingAccess() {
		return pGreeting;
	}
	
	public ParserRule getGreetingRule() {
		return getGreetingAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
