/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BrowserAutomationGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTisiAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTisiLaunchParserRuleCall_0_0 = (RuleCall)cTisiAssignment_0.eContents().get(0);
		private final Assignment cTisiAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTisiAffectationParserRuleCall_1_0 = (RuleCall)cTisiAssignment_1.eContents().get(0);
		private final Assignment cTisiAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTisiLaunchParserRuleCall_2_0 = (RuleCall)cTisiAssignment_2.eContents().get(0);
		private final Assignment cTisiAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTisiSetParserRuleCall_3_0 = (RuleCall)cTisiAssignment_3.eContents().get(0);
		private final Assignment cTisiAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTisiClickParserRuleCall_4_0 = (RuleCall)cTisiAssignment_4.eContents().get(0);
		private final Assignment cTisiAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTisiFindParserRuleCall_5_0 = (RuleCall)cTisiAssignment_5.eContents().get(0);
		
		//Model:
		//	tisi+=Launch tisi+=Affectation* tisi+=Launch? tisi+=Set* tisi+=Click* tisi+=Find*;
		@Override public ParserRule getRule() { return rule; }
		
		//tisi+=Launch tisi+=Affectation* tisi+=Launch? tisi+=Set* tisi+=Click* tisi+=Find*
		public Group getGroup() { return cGroup; }
		
		//tisi+=Launch
		public Assignment getTisiAssignment_0() { return cTisiAssignment_0; }
		
		//Launch
		public RuleCall getTisiLaunchParserRuleCall_0_0() { return cTisiLaunchParserRuleCall_0_0; }
		
		//tisi+=Affectation*
		public Assignment getTisiAssignment_1() { return cTisiAssignment_1; }
		
		//Affectation
		public RuleCall getTisiAffectationParserRuleCall_1_0() { return cTisiAffectationParserRuleCall_1_0; }
		
		//tisi+=Launch?
		public Assignment getTisiAssignment_2() { return cTisiAssignment_2; }
		
		//Launch
		public RuleCall getTisiLaunchParserRuleCall_2_0() { return cTisiLaunchParserRuleCall_2_0; }
		
		//tisi+=Set*
		public Assignment getTisiAssignment_3() { return cTisiAssignment_3; }
		
		//Set
		public RuleCall getTisiSetParserRuleCall_3_0() { return cTisiSetParserRuleCall_3_0; }
		
		//tisi+=Click*
		public Assignment getTisiAssignment_4() { return cTisiAssignment_4; }
		
		//Click
		public RuleCall getTisiClickParserRuleCall_4_0() { return cTisiClickParserRuleCall_4_0; }
		
		//tisi+=Find*
		public Assignment getTisiAssignment_5() { return cTisiAssignment_5; }
		
		//Find
		public RuleCall getTisiFindParserRuleCall_5_0() { return cTisiFindParserRuleCall_5_0; }
	}
	public class LaunchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Launch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGOTOKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUUrlParserRuleCall_1_0 = (RuleCall)cUAssignment_1.eContents().get(0);
		private final Keyword cONKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBBrowserParserRuleCall_3_0 = (RuleCall)cBAssignment_3.eContents().get(0);
		
		//Launch:
		//	'GOTO' u=Url 'ON' b=Browser
		//	//'CLICK' l1=Link 'WHERE' l2=Content 'CONTAINS' STRING 
		//	//'IS'  l=Link 'WHERE' c= Content 'CONTAINS' STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'GOTO' u=Url 'ON' b=Browser
		public Group getGroup() { return cGroup; }
		
		//'GOTO'
		public Keyword getGOTOKeyword_0() { return cGOTOKeyword_0; }
		
		//u=Url
		public Assignment getUAssignment_1() { return cUAssignment_1; }
		
		//Url
		public RuleCall getUUrlParserRuleCall_1_0() { return cUUrlParserRuleCall_1_0; }
		
		//'ON'
		public Keyword getONKeyword_2() { return cONKeyword_2; }
		
		//b=Browser
		public Assignment getBAssignment_3() { return cBAssignment_3; }
		
		//Browser
		public RuleCall getBBrowserParserRuleCall_3_0() { return cBBrowserParserRuleCall_3_0; }
	}
	public class FindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Find");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFINDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCComposantParserRuleCall_1_0 = (RuleCall)cCAssignment_1.eContents().get(0);
		private final Keyword cWHEREKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAAttributParserRuleCall_3_0 = (RuleCall)cAAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Keyword cCONTAINSKeyword_4_0 = (Keyword)cAlternatives_4.eContents().get(0);
		private final Keyword cEQUALSKeyword_4_1 = (Keyword)cAlternatives_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final RuleCall cSTRINGTerminalRuleCall_5_0 = (RuleCall)cAlternatives_5.eContents().get(0);
		private final Assignment cVAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final RuleCall cVVarRefParserRuleCall_5_1_0 = (RuleCall)cVAssignment_5_1.eContents().get(0);
		
		//Find:
		//	'FIND' c=Composant 'WHERE' a=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef);
		@Override public ParserRule getRule() { return rule; }
		
		//'FIND' c=Composant 'WHERE' a=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef)
		public Group getGroup() { return cGroup; }
		
		//'FIND'
		public Keyword getFINDKeyword_0() { return cFINDKeyword_0; }
		
		//c=Composant
		public Assignment getCAssignment_1() { return cCAssignment_1; }
		
		//Composant
		public RuleCall getCComposantParserRuleCall_1_0() { return cCComposantParserRuleCall_1_0; }
		
		//'WHERE'
		public Keyword getWHEREKeyword_2() { return cWHEREKeyword_2; }
		
		//a=Attribut
		public Assignment getAAssignment_3() { return cAAssignment_3; }
		
		//Attribut
		public RuleCall getAAttributParserRuleCall_3_0() { return cAAttributParserRuleCall_3_0; }
		
		//('CONTAINS' | 'EQUALS')
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//'CONTAINS'
		public Keyword getCONTAINSKeyword_4_0() { return cCONTAINSKeyword_4_0; }
		
		//'EQUALS'
		public Keyword getEQUALSKeyword_4_1() { return cEQUALSKeyword_4_1; }
		
		//(STRING | v=VarRef)
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_5_0() { return cSTRINGTerminalRuleCall_5_0; }
		
		//v=VarRef
		public Assignment getVAssignment_5_1() { return cVAssignment_5_1; }
		
		//VarRef
		public RuleCall getVVarRefParserRuleCall_5_1_0() { return cVVarRefParserRuleCall_5_1_0; }
	}
	public class ClickElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Click");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCLICKKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCComposantParserRuleCall_1_0 = (RuleCall)cCAssignment_1.eContents().get(0);
		private final Keyword cWHEREKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAAttributParserRuleCall_3_0 = (RuleCall)cAAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Keyword cCONTAINSKeyword_4_0 = (Keyword)cAlternatives_4.eContents().get(0);
		private final Keyword cEQUALSKeyword_4_1 = (Keyword)cAlternatives_4.eContents().get(1);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final RuleCall cSTRINGTerminalRuleCall_5_0 = (RuleCall)cAlternatives_5.eContents().get(0);
		private final Assignment cVAssignment_5_1 = (Assignment)cAlternatives_5.eContents().get(1);
		private final RuleCall cVVarRefParserRuleCall_5_1_0 = (RuleCall)cVAssignment_5_1.eContents().get(0);
		
		//Click:
		//	'CLICK' c=Composant 'WHERE' a=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef);
		@Override public ParserRule getRule() { return rule; }
		
		//'CLICK' c=Composant 'WHERE' a=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef)
		public Group getGroup() { return cGroup; }
		
		//'CLICK'
		public Keyword getCLICKKeyword_0() { return cCLICKKeyword_0; }
		
		//c=Composant
		public Assignment getCAssignment_1() { return cCAssignment_1; }
		
		//Composant
		public RuleCall getCComposantParserRuleCall_1_0() { return cCComposantParserRuleCall_1_0; }
		
		//'WHERE'
		public Keyword getWHEREKeyword_2() { return cWHEREKeyword_2; }
		
		//a=Attribut
		public Assignment getAAssignment_3() { return cAAssignment_3; }
		
		//Attribut
		public RuleCall getAAttributParserRuleCall_3_0() { return cAAttributParserRuleCall_3_0; }
		
		//('CONTAINS' | 'EQUALS')
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//'CONTAINS'
		public Keyword getCONTAINSKeyword_4_0() { return cCONTAINSKeyword_4_0; }
		
		//'EQUALS'
		public Keyword getEQUALSKeyword_4_1() { return cEQUALSKeyword_4_1; }
		
		//(STRING | v=VarRef)
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_5_0() { return cSTRINGTerminalRuleCall_5_0; }
		
		//v=VarRef
		public Assignment getVAssignment_5_1() { return cVAssignment_5_1; }
		
		//VarRef
		public RuleCall getVVarRefParserRuleCall_5_1_0() { return cVVarRefParserRuleCall_5_1_0; }
	}
	public class SetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Set");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSETKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAAttributParserRuleCall_1_0 = (RuleCall)cAAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cSTRINGTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final Assignment cVAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cVVarRefParserRuleCall_2_1_0 = (RuleCall)cVAssignment_2_1.eContents().get(0);
		private final Keyword cWHEREKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cA1Assignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cA1AttributParserRuleCall_4_0 = (RuleCall)cA1Assignment_4.eContents().get(0);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Keyword cCONTAINSKeyword_5_0 = (Keyword)cAlternatives_5.eContents().get(0);
		private final Keyword cEQUALSKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final Alternatives cAlternatives_6 = (Alternatives)cGroup.eContents().get(6);
		private final RuleCall cSTRINGTerminalRuleCall_6_0 = (RuleCall)cAlternatives_6.eContents().get(0);
		private final Assignment cVAssignment_6_1 = (Assignment)cAlternatives_6.eContents().get(1);
		private final RuleCall cVVarRefParserRuleCall_6_1_0 = (RuleCall)cVAssignment_6_1.eContents().get(0);
		
		//Set:
		//	'SET' a=Attribut (STRING | v=VarRef) 'WHERE' a1=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef);
		@Override public ParserRule getRule() { return rule; }
		
		//'SET' a=Attribut (STRING | v=VarRef) 'WHERE' a1=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef)
		public Group getGroup() { return cGroup; }
		
		//'SET'
		public Keyword getSETKeyword_0() { return cSETKeyword_0; }
		
		//a=Attribut
		public Assignment getAAssignment_1() { return cAAssignment_1; }
		
		//Attribut
		public RuleCall getAAttributParserRuleCall_1_0() { return cAAttributParserRuleCall_1_0; }
		
		//(STRING | v=VarRef)
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_0() { return cSTRINGTerminalRuleCall_2_0; }
		
		//v=VarRef
		public Assignment getVAssignment_2_1() { return cVAssignment_2_1; }
		
		//VarRef
		public RuleCall getVVarRefParserRuleCall_2_1_0() { return cVVarRefParserRuleCall_2_1_0; }
		
		//'WHERE'
		public Keyword getWHEREKeyword_3() { return cWHEREKeyword_3; }
		
		//a1=Attribut
		public Assignment getA1Assignment_4() { return cA1Assignment_4; }
		
		//Attribut
		public RuleCall getA1AttributParserRuleCall_4_0() { return cA1AttributParserRuleCall_4_0; }
		
		//('CONTAINS' | 'EQUALS')
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//'CONTAINS'
		public Keyword getCONTAINSKeyword_5_0() { return cCONTAINSKeyword_5_0; }
		
		//'EQUALS'
		public Keyword getEQUALSKeyword_5_1() { return cEQUALSKeyword_5_1; }
		
		//(STRING | v=VarRef)
		public Alternatives getAlternatives_6() { return cAlternatives_6; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_6_0() { return cSTRINGTerminalRuleCall_6_0; }
		
		//v=VarRef
		public Assignment getVAssignment_6_1() { return cVAssignment_6_1; }
		
		//VarRef
		public RuleCall getVVarRefParserRuleCall_6_1_0() { return cVVarRefParserRuleCall_6_1_0; }
	}
	public class AffectationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Affectation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cVariableParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cGETKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cAAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cAAttributParserRuleCall_2_0_1_0 = (RuleCall)cAAssignment_2_0_1.eContents().get(0);
		private final Keyword cWHEREKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cA2Assignment_2_0_3 = (Assignment)cGroup_2_0.eContents().get(3);
		private final RuleCall cA2AttributParserRuleCall_2_0_3_0 = (RuleCall)cA2Assignment_2_0_3.eContents().get(0);
		private final Alternatives cAlternatives_2_0_4 = (Alternatives)cGroup_2_0.eContents().get(4);
		private final Keyword cCONTAINSKeyword_2_0_4_0 = (Keyword)cAlternatives_2_0_4.eContents().get(0);
		private final Keyword cEQUALSKeyword_2_0_4_1 = (Keyword)cAlternatives_2_0_4.eContents().get(1);
		private final Alternatives cAlternatives_2_0_5 = (Alternatives)cGroup_2_0.eContents().get(5);
		private final RuleCall cSTRINGTerminalRuleCall_2_0_5_0 = (RuleCall)cAlternatives_2_0_5.eContents().get(0);
		private final Assignment cVAssignment_2_0_5_1 = (Assignment)cAlternatives_2_0_5.eContents().get(1);
		private final RuleCall cVVarRefParserRuleCall_2_0_5_1_0 = (RuleCall)cVAssignment_2_0_5_1.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_2_1 = (RuleCall)cAlternatives_2.eContents().get(1);
		
		//Affectation:
		//	Variable '=' ('GET' a=Attribut 'WHERE' a2=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef) | STRING);
		@Override public ParserRule getRule() { return rule; }
		
		//Variable '=' ('GET' a=Attribut 'WHERE' a2=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef) | STRING)
		public Group getGroup() { return cGroup; }
		
		//Variable
		public RuleCall getVariableParserRuleCall_0() { return cVariableParserRuleCall_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//('GET' a=Attribut 'WHERE' a2=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef) | STRING)
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'GET' a=Attribut 'WHERE' a2=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef)
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'GET'
		public Keyword getGETKeyword_2_0_0() { return cGETKeyword_2_0_0; }
		
		//a=Attribut
		public Assignment getAAssignment_2_0_1() { return cAAssignment_2_0_1; }
		
		//Attribut
		public RuleCall getAAttributParserRuleCall_2_0_1_0() { return cAAttributParserRuleCall_2_0_1_0; }
		
		//'WHERE'
		public Keyword getWHEREKeyword_2_0_2() { return cWHEREKeyword_2_0_2; }
		
		//a2=Attribut
		public Assignment getA2Assignment_2_0_3() { return cA2Assignment_2_0_3; }
		
		//Attribut
		public RuleCall getA2AttributParserRuleCall_2_0_3_0() { return cA2AttributParserRuleCall_2_0_3_0; }
		
		//('CONTAINS' | 'EQUALS')
		public Alternatives getAlternatives_2_0_4() { return cAlternatives_2_0_4; }
		
		//'CONTAINS'
		public Keyword getCONTAINSKeyword_2_0_4_0() { return cCONTAINSKeyword_2_0_4_0; }
		
		//'EQUALS'
		public Keyword getEQUALSKeyword_2_0_4_1() { return cEQUALSKeyword_2_0_4_1; }
		
		//(STRING | v=VarRef)
		public Alternatives getAlternatives_2_0_5() { return cAlternatives_2_0_5; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_0_5_0() { return cSTRINGTerminalRuleCall_2_0_5_0; }
		
		//v=VarRef
		public Assignment getVAssignment_2_0_5_1() { return cVAssignment_2_0_5_1; }
		
		//VarRef
		public RuleCall getVVarRefParserRuleCall_2_0_5_1_0() { return cVVarRefParserRuleCall_2_0_5_1_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_2_1() { return cSTRINGTerminalRuleCall_2_1; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Variable");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Variable:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class VarRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.VarRef");
		private final Assignment cVarAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarVariableCrossReference_0 = (CrossReference)cVarAssignment.eContents().get(0);
		private final RuleCall cVarVariableIDTerminalRuleCall_0_1 = (RuleCall)cVarVariableCrossReference_0.eContents().get(1);
		
		//VarRef:
		//	var=[Variable];
		@Override public ParserRule getRule() { return rule; }
		
		//var=[Variable]
		public Assignment getVarAssignment() { return cVarAssignment; }
		
		//[Variable]
		public CrossReference getVarVariableCrossReference_0() { return cVarVariableCrossReference_0; }
		
		//ID
		public RuleCall getVarVariableIDTerminalRuleCall_0_1() { return cVarVariableIDTerminalRuleCall_0_1; }
	}
	public class ComposantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Composant");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Composant:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class AttributElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Attribut");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Attribut:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class ContentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Content");
		private final Assignment cContenuAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cContenuSTRINGTerminalRuleCall_0 = (RuleCall)cContenuAssignment.eContents().get(0);
		
		//Content:
		//	contenu=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//contenu=STRING
		public Assignment getContenuAssignment() { return cContenuAssignment; }
		
		//STRING
		public RuleCall getContenuSTRINGTerminalRuleCall_0() { return cContenuSTRINGTerminalRuleCall_0; }
	}
	public class BrowserElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Browser");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Browser:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class UrlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Url");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Url:
		//	name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=STRING
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0() { return cNameSTRINGTerminalRuleCall_0; }
	}
	public class GreetingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.BrowserAutomation.Greeting");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHelloKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Greeting:
		//	'Hello' name=ID '!';
		@Override public ParserRule getRule() { return rule; }
		
		//'Hello' name=ID '!'
		public Group getGroup() { return cGroup; }
		
		//'Hello'
		public Keyword getHelloKeyword_0() { return cHelloKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'!'
		public Keyword getExclamationMarkKeyword_2() { return cExclamationMarkKeyword_2; }
	}
	
	
	private final ModelElements pModel;
	private final LaunchElements pLaunch;
	private final FindElements pFind;
	private final ClickElements pClick;
	private final SetElements pSet;
	private final AffectationElements pAffectation;
	private final VariableElements pVariable;
	private final VarRefElements pVarRef;
	private final ComposantElements pComposant;
	private final AttributElements pAttribut;
	private final ContentElements pContent;
	private final BrowserElements pBrowser;
	private final UrlElements pUrl;
	private final GreetingElements pGreeting;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BrowserAutomationGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pLaunch = new LaunchElements();
		this.pFind = new FindElements();
		this.pClick = new ClickElements();
		this.pSet = new SetElements();
		this.pAffectation = new AffectationElements();
		this.pVariable = new VariableElements();
		this.pVarRef = new VarRefElements();
		this.pComposant = new ComposantElements();
		this.pAttribut = new AttributElements();
		this.pContent = new ContentElements();
		this.pBrowser = new BrowserElements();
		this.pUrl = new UrlElements();
		this.pGreeting = new GreetingElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.BrowserAutomation".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	tisi+=Launch tisi+=Affectation* tisi+=Launch? tisi+=Set* tisi+=Click* tisi+=Find*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Launch:
	//	'GOTO' u=Url 'ON' b=Browser
	//	//'CLICK' l1=Link 'WHERE' l2=Content 'CONTAINS' STRING 
	//	//'IS'  l=Link 'WHERE' c= Content 'CONTAINS' STRING
	//;
	public LaunchElements getLaunchAccess() {
		return pLaunch;
	}
	
	public ParserRule getLaunchRule() {
		return getLaunchAccess().getRule();
	}
	
	//Find:
	//	'FIND' c=Composant 'WHERE' a=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef);
	public FindElements getFindAccess() {
		return pFind;
	}
	
	public ParserRule getFindRule() {
		return getFindAccess().getRule();
	}
	
	//Click:
	//	'CLICK' c=Composant 'WHERE' a=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef);
	public ClickElements getClickAccess() {
		return pClick;
	}
	
	public ParserRule getClickRule() {
		return getClickAccess().getRule();
	}
	
	//Set:
	//	'SET' a=Attribut (STRING | v=VarRef) 'WHERE' a1=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef);
	public SetElements getSetAccess() {
		return pSet;
	}
	
	public ParserRule getSetRule() {
		return getSetAccess().getRule();
	}
	
	//Affectation:
	//	Variable '=' ('GET' a=Attribut 'WHERE' a2=Attribut ('CONTAINS' | 'EQUALS') (STRING | v=VarRef) | STRING);
	public AffectationElements getAffectationAccess() {
		return pAffectation;
	}
	
	public ParserRule getAffectationRule() {
		return getAffectationAccess().getRule();
	}
	
	//Variable:
	//	name=ID;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//VarRef:
	//	var=[Variable];
	public VarRefElements getVarRefAccess() {
		return pVarRef;
	}
	
	public ParserRule getVarRefRule() {
		return getVarRefAccess().getRule();
	}
	
	//Composant:
	//	name=ID;
	public ComposantElements getComposantAccess() {
		return pComposant;
	}
	
	public ParserRule getComposantRule() {
		return getComposantAccess().getRule();
	}
	
	//Attribut:
	//	name=ID;
	public AttributElements getAttributAccess() {
		return pAttribut;
	}
	
	public ParserRule getAttributRule() {
		return getAttributAccess().getRule();
	}
	
	//Content:
	//	contenu=STRING;
	public ContentElements getContentAccess() {
		return pContent;
	}
	
	public ParserRule getContentRule() {
		return getContentAccess().getRule();
	}
	
	//Browser:
	//	name=ID;
	public BrowserElements getBrowserAccess() {
		return pBrowser;
	}
	
	public ParserRule getBrowserRule() {
		return getBrowserAccess().getRule();
	}
	
	//Url:
	//	name=STRING;
	public UrlElements getUrlAccess() {
		return pUrl;
	}
	
	public ParserRule getUrlRule() {
		return getUrlAccess().getRule();
	}
	
	//Greeting:
	//	'Hello' name=ID '!';
	public GreetingElements getGreetingAccess() {
		return pGreeting;
	}
	
	public ParserRule getGreetingRule() {
		return getGreetingAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
