/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserAutomationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browserAutomation";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/BrowserAutomation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browserAutomation";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserAutomationPackage eINSTANCE = org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.ModelImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Tisi</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TISI = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.TestImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getTest()
   * @generated
   */
  int TEST = 1;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__B = 0;

  /**
   * The feature id for the '<em><b>U</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__U = 1;

  /**
   * The feature id for the '<em><b>A1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__A1 = 2;

  /**
   * The feature id for the '<em><b>A2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__A2 = 3;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl <em>Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getBrowser()
   * @generated
   */
  int BROWSER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER__NAME = 0;

  /**
   * The number of structural features of the '<em>Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.UrlImpl <em>Url</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.UrlImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getUrl()
   * @generated
   */
  int URL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__NAME = 0;

  /**
   * The number of structural features of the '<em>Url</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.AttributImpl <em>Attribut</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.AttributImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAttribut()
   * @generated
   */
  int ATTRIBUT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__NAME = 0;

  /**
   * The number of structural features of the '<em>Attribut</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl <em>Greeting</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getGreeting()
   * @generated
   */
  int GREETING = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETING__NAME = 0;

  /**
   * The number of structural features of the '<em>Greeting</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETING_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.browserAutomation.Model#getTisi <em>Tisi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tisi</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Model#getTisi()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tisi();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Test#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>B</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Test#getB()
   * @see #getTest()
   * @generated
   */
  EReference getTest_B();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Test#getU <em>U</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>U</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Test#getU()
   * @see #getTest()
   * @generated
   */
  EReference getTest_U();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Test#getA1 <em>A1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A1</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Test#getA1()
   * @see #getTest()
   * @generated
   */
  EReference getTest_A1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Test#getA2 <em>A2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A2</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Test#getA2()
   * @see #getTest()
   * @generated
   */
  EReference getTest_A2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Browser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Browser
   * @generated
   */
  EClass getBrowser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Browser#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Browser#getName()
   * @see #getBrowser()
   * @generated
   */
  EAttribute getBrowser_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Url <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Url</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Url
   * @generated
   */
  EClass getUrl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Url#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Url#getName()
   * @see #getUrl()
   * @generated
   */
  EAttribute getUrl_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Attribut <em>Attribut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribut</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Attribut
   * @generated
   */
  EClass getAttribut();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Attribut#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Attribut#getName()
   * @see #getAttribut()
   * @generated
   */
  EAttribute getAttribut_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Greeting <em>Greeting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greeting</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Greeting
   * @generated
   */
  EClass getGreeting();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Greeting#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Greeting#getName()
   * @see #getGreeting()
   * @generated
   */
  EAttribute getGreeting_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserAutomationFactory getBrowserAutomationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.ModelImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Tisi</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TISI = eINSTANCE.getModel_Tisi();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.TestImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__B = eINSTANCE.getTest_B();

    /**
     * The meta object literal for the '<em><b>U</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__U = eINSTANCE.getTest_U();

    /**
     * The meta object literal for the '<em><b>A1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__A1 = eINSTANCE.getTest_A1();

    /**
     * The meta object literal for the '<em><b>A2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__A2 = eINSTANCE.getTest_A2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl <em>Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getBrowser()
     * @generated
     */
    EClass BROWSER = eINSTANCE.getBrowser();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROWSER__NAME = eINSTANCE.getBrowser_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.UrlImpl <em>Url</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.UrlImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getUrl()
     * @generated
     */
    EClass URL = eINSTANCE.getUrl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute URL__NAME = eINSTANCE.getUrl_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.AttributImpl <em>Attribut</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.AttributImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAttribut()
     * @generated
     */
    EClass ATTRIBUT = eINSTANCE.getAttribut();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUT__NAME = eINSTANCE.getAttribut_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl <em>Greeting</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getGreeting()
     * @generated
     */
    EClass GREETING = eINSTANCE.getGreeting();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREETING__NAME = eINSTANCE.getGreeting_Name();

  }

} //BrowserAutomationPackage
