/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserAutomationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browserAutomation";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/BrowserAutomation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browserAutomation";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserAutomationPackage eINSTANCE = org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.ModelImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Tisi</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TISI = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.LaunchImpl <em>Launch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.LaunchImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getLaunch()
   * @generated
   */
  int LAUNCH = 1;

  /**
   * The feature id for the '<em><b>U</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAUNCH__U = 0;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAUNCH__B = 1;

  /**
   * The number of structural features of the '<em>Launch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAUNCH_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.FindImpl <em>Find</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.FindImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getFind()
   * @generated
   */
  int FIND = 2;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND__C = 0;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND__A = 1;

  /**
   * The feature id for the '<em><b>V</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND__V = 2;

  /**
   * The number of structural features of the '<em>Find</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.ClickImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getClick()
   * @generated
   */
  int CLICK = 3;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__C = 0;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__A = 1;

  /**
   * The feature id for the '<em><b>V</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__V = 2;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.SetImpl <em>Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.SetImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getSet()
   * @generated
   */
  int SET = 4;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET__A = 0;

  /**
   * The feature id for the '<em><b>V</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET__V = 1;

  /**
   * The feature id for the '<em><b>A1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET__A1 = 2;

  /**
   * The number of structural features of the '<em>Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.AffectationImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 5;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.VariableImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 6;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__A = AFFECTATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>A2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__A2 = AFFECTATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>V</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__V = AFFECTATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = AFFECTATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = AFFECTATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.VarRefImpl <em>Var Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.VarRefImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVarRef()
   * @generated
   */
  int VAR_REF = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF__VAR = 0;

  /**
   * The number of structural features of the '<em>Var Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ComposantImpl <em>Composant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.ComposantImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getComposant()
   * @generated
   */
  int COMPOSANT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSANT__NAME = 0;

  /**
   * The number of structural features of the '<em>Composant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSANT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.AttributImpl <em>Attribut</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.AttributImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAttribut()
   * @generated
   */
  int ATTRIBUT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__NAME = 0;

  /**
   * The number of structural features of the '<em>Attribut</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.ContentImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 10;

  /**
   * The feature id for the '<em><b>Contenu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT__CONTENU = 0;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl <em>Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getBrowser()
   * @generated
   */
  int BROWSER = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER__NAME = 0;

  /**
   * The number of structural features of the '<em>Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BROWSER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.UrlImpl <em>Url</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.UrlImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getUrl()
   * @generated
   */
  int URL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL__NAME = 0;

  /**
   * The number of structural features of the '<em>Url</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int URL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl <em>Greeting</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl
   * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getGreeting()
   * @generated
   */
  int GREETING = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETING__NAME = 0;

  /**
   * The number of structural features of the '<em>Greeting</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREETING_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.browserAutomation.Model#getTisi <em>Tisi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tisi</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Model#getTisi()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Tisi();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Launch <em>Launch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Launch</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Launch
   * @generated
   */
  EClass getLaunch();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Launch#getU <em>U</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>U</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Launch#getU()
   * @see #getLaunch()
   * @generated
   */
  EReference getLaunch_U();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Launch#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>B</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Launch#getB()
   * @see #getLaunch()
   * @generated
   */
  EReference getLaunch_B();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Find <em>Find</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Find</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Find
   * @generated
   */
  EClass getFind();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Find#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Find#getC()
   * @see #getFind()
   * @generated
   */
  EReference getFind_C();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Find#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Find#getA()
   * @see #getFind()
   * @generated
   */
  EReference getFind_A();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Find#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Find#getV()
   * @see #getFind()
   * @generated
   */
  EReference getFind_V();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Click#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Click#getC()
   * @see #getClick()
   * @generated
   */
  EReference getClick_C();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Click#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Click#getA()
   * @see #getClick()
   * @generated
   */
  EReference getClick_A();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Click#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Click#getV()
   * @see #getClick()
   * @generated
   */
  EReference getClick_V();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Set <em>Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Set
   * @generated
   */
  EClass getSet();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Set#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Set#getA()
   * @see #getSet()
   * @generated
   */
  EReference getSet_A();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Set#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Set#getV()
   * @see #getSet()
   * @generated
   */
  EReference getSet_V();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Set#getA1 <em>A1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A1</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Set#getA1()
   * @see #getSet()
   * @generated
   */
  EReference getSet_A1();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Variable#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Variable#getA()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_A();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Variable#getA2 <em>A2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A2</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Variable#getA2()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_A2();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.browserAutomation.Variable#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Variable#getV()
   * @see #getVariable()
   * @generated
   */
  EReference getVariable_V();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.VarRef <em>Var Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Ref</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.VarRef
   * @generated
   */
  EClass getVarRef();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.browserAutomation.VarRef#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.VarRef#getVar()
   * @see #getVarRef()
   * @generated
   */
  EReference getVarRef_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Composant <em>Composant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composant</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Composant
   * @generated
   */
  EClass getComposant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Composant#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Composant#getName()
   * @see #getComposant()
   * @generated
   */
  EAttribute getComposant_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Attribut <em>Attribut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribut</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Attribut
   * @generated
   */
  EClass getAttribut();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Attribut#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Attribut#getName()
   * @see #getAttribut()
   * @generated
   */
  EAttribute getAttribut_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Content#getContenu <em>Contenu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contenu</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Content#getContenu()
   * @see #getContent()
   * @generated
   */
  EAttribute getContent_Contenu();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Browser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Browser</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Browser
   * @generated
   */
  EClass getBrowser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Browser#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Browser#getName()
   * @see #getBrowser()
   * @generated
   */
  EAttribute getBrowser_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Url <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Url</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Url
   * @generated
   */
  EClass getUrl();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Url#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Url#getName()
   * @see #getUrl()
   * @generated
   */
  EAttribute getUrl_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.browserAutomation.Greeting <em>Greeting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greeting</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Greeting
   * @generated
   */
  EClass getGreeting();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.browserAutomation.Greeting#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.browserAutomation.Greeting#getName()
   * @see #getGreeting()
   * @generated
   */
  EAttribute getGreeting_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserAutomationFactory getBrowserAutomationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.ModelImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Tisi</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TISI = eINSTANCE.getModel_Tisi();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.LaunchImpl <em>Launch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.LaunchImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getLaunch()
     * @generated
     */
    EClass LAUNCH = eINSTANCE.getLaunch();

    /**
     * The meta object literal for the '<em><b>U</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAUNCH__U = eINSTANCE.getLaunch_U();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAUNCH__B = eINSTANCE.getLaunch_B();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.FindImpl <em>Find</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.FindImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getFind()
     * @generated
     */
    EClass FIND = eINSTANCE.getFind();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIND__C = eINSTANCE.getFind_C();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIND__A = eINSTANCE.getFind_A();

    /**
     * The meta object literal for the '<em><b>V</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIND__V = eINSTANCE.getFind_V();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.ClickImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__C = eINSTANCE.getClick_C();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__A = eINSTANCE.getClick_A();

    /**
     * The meta object literal for the '<em><b>V</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__V = eINSTANCE.getClick_V();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.SetImpl <em>Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.SetImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getSet()
     * @generated
     */
    EClass SET = eINSTANCE.getSet();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET__A = eINSTANCE.getSet_A();

    /**
     * The meta object literal for the '<em><b>V</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET__V = eINSTANCE.getSet_V();

    /**
     * The meta object literal for the '<em><b>A1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SET__A1 = eINSTANCE.getSet_A1();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.AffectationImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.VariableImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__A = eINSTANCE.getVariable_A();

    /**
     * The meta object literal for the '<em><b>A2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__A2 = eINSTANCE.getVariable_A2();

    /**
     * The meta object literal for the '<em><b>V</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE__V = eINSTANCE.getVariable_V();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.VarRefImpl <em>Var Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.VarRefImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getVarRef()
     * @generated
     */
    EClass VAR_REF = eINSTANCE.getVarRef();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_REF__VAR = eINSTANCE.getVarRef_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ComposantImpl <em>Composant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.ComposantImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getComposant()
     * @generated
     */
    EClass COMPOSANT = eINSTANCE.getComposant();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSANT__NAME = eINSTANCE.getComposant_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.AttributImpl <em>Attribut</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.AttributImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getAttribut()
     * @generated
     */
    EClass ATTRIBUT = eINSTANCE.getAttribut();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUT__NAME = eINSTANCE.getAttribut_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.ContentImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '<em><b>Contenu</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTENT__CONTENU = eINSTANCE.getContent_Contenu();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl <em>Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getBrowser()
     * @generated
     */
    EClass BROWSER = eINSTANCE.getBrowser();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BROWSER__NAME = eINSTANCE.getBrowser_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.UrlImpl <em>Url</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.UrlImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getUrl()
     * @generated
     */
    EClass URL = eINSTANCE.getUrl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute URL__NAME = eINSTANCE.getUrl_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl <em>Greeting</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.browserAutomation.impl.GreetingImpl
     * @see org.xtext.example.mydsl.browserAutomation.impl.BrowserAutomationPackageImpl#getGreeting()
     * @generated
     */
    EClass GREETING = eINSTANCE.getGreeting();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREETING__NAME = eINSTANCE.getGreeting_Name();

  }

} //BrowserAutomationPackage
