/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Content#getContenu <em>Contenu</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getContent()
 * @model
 * @generated
 */
public interface Content extends EObject
{
  /**
   * Returns the value of the '<em><b>Contenu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contenu</em>' attribute.
   * @see #setContenu(String)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getContent_Contenu()
   * @model
   * @generated
   */
  String getContenu();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Content#getContenu <em>Contenu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contenu</em>' attribute.
   * @see #getContenu()
   * @generated
   */
  void setContenu(String value);

} // Content
