/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Launch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Launch#getU <em>U</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Launch#getB <em>B</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getLaunch()
 * @model
 * @generated
 */
public interface Launch extends EObject
{
  /**
   * Returns the value of the '<em><b>U</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>U</em>' containment reference.
   * @see #setU(Url)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getLaunch_U()
   * @model containment="true"
   * @generated
   */
  Url getU();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Launch#getU <em>U</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>U</em>' containment reference.
   * @see #getU()
   * @generated
   */
  void setU(Url value);

  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference.
   * @see #setB(Browser)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getLaunch_B()
   * @model containment="true"
   * @generated
   */
  Browser getB();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Launch#getB <em>B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' containment reference.
   * @see #getB()
   * @generated
   */
  void setB(Browser value);

} // Launch
