/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Set#getA <em>A</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Set#getS1 <em>S1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Set#getV1 <em>V1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Set#getA1 <em>A1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Set#getS2 <em>S2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Set#getV2 <em>V2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet()
 * @model
 * @generated
 */
public interface Set extends EObject
{
  /**
   * Returns the value of the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' containment reference.
   * @see #setA(Attribut)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet_A()
   * @model containment="true"
   * @generated
   */
  Attribut getA();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Set#getA <em>A</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' containment reference.
   * @see #getA()
   * @generated
   */
  void setA(Attribut value);

  /**
   * Returns the value of the '<em><b>S1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S1</em>' attribute.
   * @see #setS1(String)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet_S1()
   * @model
   * @generated
   */
  String getS1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Set#getS1 <em>S1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S1</em>' attribute.
   * @see #getS1()
   * @generated
   */
  void setS1(String value);

  /**
   * Returns the value of the '<em><b>V1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V1</em>' containment reference.
   * @see #setV1(VarRef)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet_V1()
   * @model containment="true"
   * @generated
   */
  VarRef getV1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Set#getV1 <em>V1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V1</em>' containment reference.
   * @see #getV1()
   * @generated
   */
  void setV1(VarRef value);

  /**
   * Returns the value of the '<em><b>A1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>A1</em>' containment reference.
   * @see #setA1(Attribut)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet_A1()
   * @model containment="true"
   * @generated
   */
  Attribut getA1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Set#getA1 <em>A1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A1</em>' containment reference.
   * @see #getA1()
   * @generated
   */
  void setA1(Attribut value);

  /**
   * Returns the value of the '<em><b>S2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S2</em>' attribute.
   * @see #setS2(String)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet_S2()
   * @model
   * @generated
   */
  String getS2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Set#getS2 <em>S2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S2</em>' attribute.
   * @see #getS2()
   * @generated
   */
  void setS2(String value);

  /**
   * Returns the value of the '<em><b>V2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V2</em>' containment reference.
   * @see #setV2(VarRef)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getSet_V2()
   * @model containment="true"
   * @generated
   */
  VarRef getV2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Set#getV2 <em>V2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V2</em>' containment reference.
   * @see #getV2()
   * @generated
   */
  void setV2(VarRef value);

} // Set
