/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Test#getB <em>B</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Test#getU <em>U</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Test#getA1 <em>A1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.Test#getA2 <em>A2</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getTest()
 * @model
 * @generated
 */
public interface Test extends EObject
{
  /**
   * Returns the value of the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' containment reference.
   * @see #setB(Browser)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getTest_B()
   * @model containment="true"
   * @generated
   */
  Browser getB();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Test#getB <em>B</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' containment reference.
   * @see #getB()
   * @generated
   */
  void setB(Browser value);

  /**
   * Returns the value of the '<em><b>U</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>U</em>' containment reference.
   * @see #setU(Url)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getTest_U()
   * @model containment="true"
   * @generated
   */
  Url getU();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Test#getU <em>U</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>U</em>' containment reference.
   * @see #getU()
   * @generated
   */
  void setU(Url value);

  /**
   * Returns the value of the '<em><b>A1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>A1</em>' containment reference.
   * @see #setA1(Attribut)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getTest_A1()
   * @model containment="true"
   * @generated
   */
  Attribut getA1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Test#getA1 <em>A1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A1</em>' containment reference.
   * @see #getA1()
   * @generated
   */
  void setA1(Attribut value);

  /**
   * Returns the value of the '<em><b>A2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>A2</em>' containment reference.
   * @see #setA2(Attribut)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getTest_A2()
   * @model containment="true"
   * @generated
   */
  Attribut getA2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.Test#getA2 <em>A2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A2</em>' containment reference.
   * @see #getA2()
   * @generated
   */
  void setA2(Attribut value);

} // Test
