/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.browserAutomation;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.browserAutomation.VarRef#getVa <em>Va</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getVarRef()
 * @model
 * @generated
 */
public interface VarRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Va</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Va</em>' reference.
   * @see #setVa(Variable)
   * @see org.xtext.example.mydsl.browserAutomation.BrowserAutomationPackage#getVarRef_Va()
   * @model
   * @generated
   */
  Variable getVa();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.browserAutomation.VarRef#getVa <em>Va</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Va</em>' reference.
   * @see #getVa()
   * @generated
   */
  void setVa(Variable value);

} // VarRef
